#!/usr/bin/env bash

# Script to swap out PHP versions using Homebrew on macOS

if eval php -v | grep "PHP 8.2" >> /dev/null; then
	echo "You are running PHP 8.2. Switching to 8.0."
	brew unlink php >> /dev/null && brew link php@8.0 >> /dev/null
elif eval php -v | grep "PHP 8.0" >> /dev/null; then
	echo "You are running PHP 8.0. Switching to 8.2."
	brew unlink php@8.0 >> /dev/null && brew link php >> /dev/null
fi

# Report the new running version
version=$(php -v)
echo -e "\nYou are now running ${version:0:7}."